version: "3.3"

services:
  zookeeper:
    container_name: neu_zookeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    container_name: neu_kafka
    image: wurstmeister/kafka:2.12-2.5.0
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test:2:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  consumer1:
    build:
      context: ./consumer1
    container_name: pubsub_consumer1
    volumes:
      - ./consumer1/src:/app/src
  consumer2:
    build:
      context: ./consumer2
    container_name: pubsub_consumer2
    volumes:
      - ./consumer2/src:/app/src

  producer:
    build:
      context: ./producer
    container_name: pubsub_producer
    volumes:
      - ./producer/src:/app/src

networks:
  neu:
